baseURL = 'https://zcar.tech/'
languageCode = 'zh-cn'
title = 'Z小时光'
theme = 'hugo-theme-cleanwhite'
preserveTaxonomyNames = true
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[outputs]
home = ["HTML", "RSS"]

[params]
  author = "张思浩 (老张)"
  description = "张思浩的博客，分享原创技术文章、自驾、越野、改装车（BJ40、斯巴鲁BRZ）等内容。"
  keywords = ["张思浩", "老张", "博客", "技术", "自驾", "越野", "改装车", "BJ40", "斯巴鲁BRZ", "后端", "嵌入式", "AI", "安卓"]
  header_title = "Z小时光"
  header_subtitle = "记录技术、自驾与生活"
  omit_categories = false
  featured_tags = true
  featured_condition_size = 1
  [params.social]
  email = "jasper.zsh@hotmail.com"
  github = "https://github.com/jasper-zsh"

  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"